echo \
"CANDIDE_SECURITY_PORT=${CANDIDE_SECURITY_PORT:-3004}
CANDIDE_SECURITY_MONGODB_URL=${CANDIDE_SECURITY_MONGODB_URL:-mongodb://localhost:27017/security}
CANDIDE_SECURITY_BUNDLER_URL=${CANDIDE_SECURITY_BUNDLER_URL:-http://10.0.2.2:3002}
CANDIDE_SECURITY_ALCHEMY_GOERLI_RPC=${CANDIDE_SECURITY_ALCHEMY_GOERLI_RPC:-}
CANDIDE_SECURITY_SENTRY_DSN=${CANDIDE_SECURITY_SENTRY_DSN}" \
> .env

echo "Env files successfully generated."
